### ISSUE TITLE
Cannot read property 'namespace' of undefined at exports.handler (/var/task/index.js:10:25)

### ISSUE THREAD

**Issue by BDM98** [kate-hall/alexa-icomfort#19]
This is the error I get when attempting to enable the skill for Alexa. I'm not sure where to go from here with this? (I'm not a programmer by any means...) I think I have the rest of it setup correctly, I've been through your wiki 3 times now and can't find anything I did incorrectly, so I'm at a loss for what to do next.

Thanks!

**Comment by kate-hall** [comment]
Hi @BDM98! ~~Where do you see this error pop up? Can you include a screenshot, if possible? I'm working on getting this up and running with the V3 payload message format and would love to help you sort this one out.~~ Ignore, it's definitely from choosing the V3 payload, I'll have a fix up shortly and will update this thread once I have a new version of the code available.

**Comment by BDM98** [comment]
Thanks Kate! If I can help, please let me know!!

**Comment by StarfighterJ** [comment]
Nice Kate that might  fix my Not Discovering Devices issue on the V3 payload.
