### ISSUE TITLE
Code Preparation Question

### ISSUE THREAD

**Issue by StarfighterJ** [kate-hall/alexa-icomfort#20]
Save your changes and zip the contents of the src folder. Do NOT include the src folder itself, just the contents! 
Are we Suppose to include the node_modules Folder in the Zip file?

**Comment by kate-hall** [comment]
Yep! Include the `node_modules`. 

Sorry for my slowness, I'm still working on a v3 fix, if you want to try out what I've got so far it's in this branch: https://github.com/kate-hall/alexa-icomfort/tree/v3

Note that I haven't finished the "Alexa, turn up temperature" style commands, only setting by exact degree. There have been some massive changes in how Alexa interfaces with thermostats and mapping it to Lennox's (slightly) clunky system is tricky.

**Comment by StarfighterJ** [comment]
I played around with the V3 new code still can't discover it Also I ran a LAMBDA test and got this result See attached:
![2018-01-11](https://user-images.githubusercontent.com/29153197/34845788-1b4252ea-f6e4-11e7-8960-46403666592f.png)

**Comment by jwsattler** [comment]
Hi Kate, firstly - a great initiative, thanks!

I've followed all the instructions and release notes, and think I'm close to getting it working.  I can successfully do a lambda test with your earlier code branch (although if I try with the v3 branch I get the same error as StarfighterJ).

The one issue I have is with device discovery.  Amazon no longer allows new deployments of v2 smart home skill APIs.   I can only deploy v3.   Any thoughts on if this is likely to be the issue with device discovery?  In which case I guess I should wait until you've found time to iron out a new release?  

Thanks again for the great work.

**Comment by cmarkovitz** [comment]
@jwsattler if you try it with the new code - @kate-hall  just merged a branch - it will work with v3 AND multiple zones

**Comment by StarfighterJ** [comment]
I see the V3 zip to download but it hasn't been updated since 27 DEC 2017 has this been updated since my last test?

**Comment by kate-hall** [comment]
@StarfighterJ I'm closing this ticket and we can correspond in the newer one!
