### ISSUE TITLE
icomfort V3

### ISSUE THREAD

**Issue by StarfighterJ** [kate-hall/alexa-icomfort#22]
Hi Kate is the new V3 dated 27 December 2017 the latest in the Download area Good to go now?

**Comment by barwin** [comment]
@StarfighterJ - the master branch of this repo is v3-ready. Just 'clone or download' the repo and you should be able to follow Kate's setup instructions from there.

![image](https://user-images.githubusercontent.com/3289/37987847-31a3e1a6-31b4-11e8-8360-fb2551bb6ad6.png)

**Comment by StarfighterJ** [comment]
I can't get it to Discover and when I run a Lamba test I get this: Please help What am I doing wrong. FYI in the Development the are where to Put Privacy Policy: https://ve0kyj5tp5.execute-api.us-east-1.amazonaws.com/test/PrivacyPolicy (any value is fine) is no longer there?
![2018-04-05](https://user-images.githubusercontent.com/29153197/38391646-d734dda6-38f2-11e8-8060-096f9b1803a7.png)

**Comment by kate-hall** [comment]
What's in the test you're running? I see that it's called LennoxAdapter, but without seeing that code I'm clueless as to why it's failing. 

Also: the setup instructions have changed significantly with this version, did you delete the original and start over? That might be the best way of ensuring the correct setup.

**Comment by kate-hall** [comment]
@StarfighterJ I have a feeling you're using the default Discovery test JSON object in the Lambda...which is outdated.

Can you try this instead (replace the code in `LennoxAdapter` > `Configure test events` with the following):

```
{ 
    "directive": { 
        "header": {
            "namespace": "Alexa.Discovery",
            "name": "Discover",
            "payloadVersion": "3",
            "messageId": "4d92adf0-881b-4507-90bb-e5b8f5385249" 
        },
        "payload": { 
            "scope": {
                "type": "BearerToken",
                "token": "AnythingCanBeAToken"
            }
            
        } 
    } 
}
```

Run the test again, and post the full execution results. I just removed my own device and reran discovery and was able to find my thermostat, so I don't think the code's broken.

**Comment by StarfighterJ** [comment]
Holy Smoke I deleted everything and Started over and every thing works now Thanks a Bunch Kate

**Comment by kate-hall** [comment]
Hooray! Glad you got it working!
