### ISSUE TITLE
FYI Alexa Developer and ASW Lambda has Change alot

### ISSUE THREAD

**Issue by StarfighterJ** [kate-hall/alexa-icomfort#25]
Kate FYI Alexa Developer and ASW Lambda has Change a lot the Set up's to follow might need to be changed.

**Comment by piconut** [comment]
Ditto, just tried to set things up and more of it has changed, than remained the same.  I got stuck at Wiki step 3 > AWS Setup > #4 Paste alexa-smart-home-skill-adapter into the Search box. Select the blueprint with this name.

No blueprint comes up.  I even tried manually looking through all the available blueprints and nothing comes close to matching "alexa-smart-home-skill-adapter"

Please help!

**Comment by kate-hall** [comment]
@piconut StarfighterJ was able to set up the skill back in April when I revised the directions, I'll take a look again and rewrite them as soon as I'm able! This skill was just for fun, so I don't have a ton of time to maintain it but I'll do my best to fix it up soon, I appreciate knowing the instructions are (yet again) out of date :)

**Comment by piconut** [comment]
Thank you for your help on this Kate!   I have a 4 zone system but I would be happy to just be able to change the temperature in the main zone using Alexa (which if I understand correctly, is how this script works).
