### ISSUE TITLE
Could you provide an update to the Lambda section of the instructions?

### ISSUE THREAD

**Issue by rehype02** [kate-hall/alexa-icomfort#28]
I got stuck at Wiki step 3 > AWS Setup > #4 Paste alexa-smart-home-skill-adapter into the Search box. Select the blueprint with this name.

No blueprint comes up. I even tried manually looking through all the available blueprints and nothing comes close to matching "alexa-smart-home-skill-adapter"

The only section I can find this key is if I choose the AWS Serverless Application Repository instead of blueprint. 

Any help you could provide would be greatly appreciated. You did a really amazing job with this and its appreciated.

**Comment by vlazyman** [comment]
Just use the AWS Serverless Application Repository instead. I don't think it really matters anyway since everything gets overwritten with the zipped code but I could be wrong.
Anyway, that's what I did and it all worked.

**Comment by kate-hall** [comment]
@rehype02 sorry I was so slow to do this, I've revised the wiki from the ground up and it should match the AWS portal interface now.
