### ISSUE TITLE
Implement Celsius/Fahrenheit detection

### ISSUE THREAD

**Issue by kate-hall** [kate-hall/alexa-icomfort#3]
This skill should detect whether your thermostat uses Celsius or Fahrenheit measurements and respond accordingly. (Currently works for Fahrenheit setups only)

**Comment by benrjunk** [comment]
Hi.

Could you send me the code to change this to deg C from deg F?

Thanks,

Ben

**Comment by kate-hall** [comment]
Hi @benrjunk, I'll work on that next and let you know when it's ready!

**Comment by kate-hall** [comment]
Hey @benrjunk, turns out this skill already works with Celsius! Same code. If your Alexa is reading out temperatures in Farenheit, go to your Alexa app or http://alexa.amazon.com, then Settings, then your Device. Scroll to the bottom, and toggle Temperature Units to On.

See screenshot:
![img_5322](https://cloud.githubusercontent.com/assets/8494775/23149244/7ac1c7fe-f79f-11e6-9ba3-2976c1bf5678.PNG)
